#/bin/bash 

set -x # Print commands and their arguments as they are executed
set -e # Exit immediately if a command exits with a non-zero status

# Copy the source files to the api folder
copy_file () {

    # Add a warning to the top of the file
    echo "// AUTOGENERATED FILE DO NOT EDIT" > $2
    echo "// SOURCE FILE: ${1:2}" >> $2

    # Append the source file to the destination file
    cat $1 >> $2
}

copy_file ./pkg/users.go ./api/users.go
copy_file ./pkg/users/users.go ./api/users/[id].go

# vercel --prod